/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        "on-surface-variant": "#b9cacb",
        "on-secondary-fixed": "#1a1b26",
        "inverse-on-surface": "#2c303a",
        "tertiary-fixed-dim": "#d1bcff",
        "primary-fixed-dim": "#00dbe7",
        "outline": "#849495",
        "surface-variant": "#31353f",
        "surface-dim": "#0f131c",
        "on-error": "#690005",
        "surface-container": "#1c1f29",
        "surface-container-highest": "#31353f",
        "on-primary-fixed": "#002022",
        "surface-bright": "#353943",
        "inverse-primary": "#00696f",
        "on-tertiary-fixed": "#23005b",
        "error": "#ffb4ab",
        "primary": "#e1fdff",
        "on-surface": "#dfe2ef",
        "secondary": "#c6c5d4",
        "secondary-fixed-dim": "#c6c5d4",
        "on-secondary-fixed-variant": "#454652",
        "primary-container": "#00f2ff",
        "outline-variant": "#3a494b",
        "on-secondary-container": "#b8b7c6",
        "surface-container-lowest": "#0a0e17",
        "surface-container-low": "#181b25",
        "on-error-container": "#ffdad6",
        "background": "#0f131c",
        "surface-container-high": "#262a34",
        "on-tertiary-fixed-variant": "#5700c9",
        "error-container": "#93000a",
        "on-secondary": "#2f303b",
        "on-primary-fixed-variant": "#004f54",
        "on-background": "#dfe2ef",
        "surface": "#0f131c",
        "secondary-container": "#484855",
        "on-primary-container": "#006a71",
        "tertiary-fixed": "#e9ddff",
        "surface-tint": "#00dbe7",
        "inverse-surface": "#dfe2ef",
        "primary-fixed": "#74f5ff",
        "secondary-fixed": "#e2e1f1",
        "tertiary-container": "#e3d4ff",
        "on-tertiary": "#3c0090",
        "tertiary": "#fcf5ff",
        "on-primary": "#00363a",
        "on-tertiary-container": "#7318ff"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        "full": "9999px"
      },
      spacing: {
        "iris_size": "240px",
        "gutter": "8px",
        "margin": "16px"
      },
      fontFamily: {
        "label-caps": ["JetBrains Mono", "monospace"],
        "body-sm": ["Inter", "sans-serif"],
        "mono-data": ["JetBrains Mono", "monospace"],
        "headline-lg": ["JetBrains Mono", "monospace"],
        "body-md": ["Inter", "sans-serif"],
        "headline-sm": ["JetBrains Mono", "monospace"],
        "display-iris": ["JetBrains Mono", "monospace"]
      }
    },
  },
  plugins: [],
}
